### ISSUE TITLE
Django 1.10 release

### ISSUE THREAD

**Issue by Budek** [mlavin/django-selectable#177] opened 2016-12-28 14:05 UTC
(...)lib/python2.7/site-packages/selectable/forms/fields.py:27: RemovedInDjango110Warning: `BaseAutoCompleteField._has_changed` method should be renamed `has_changed`.
  class BaseAutoCompleteField(forms.Field):

Can you create new version (0.10?) and send it to pypi?

**Comment by hugorodgerbrown** [comment] 2016-12-30 17:13
+1 for this.

**Comment by raphaelmerx** [comment] 2017-02-22 06:58
@mlavin any idea when a Django 1.10 compatible version will be pushed to pypi? The current master branch is compatible with 1.10.

**Comment by mlavin** [comment] 2017-02-24 13:39
The test suite passes but there are outstanding issues on the client side/admin which I haven't had time to address (#155, #167, #179, #183). It just isn't a priority for me :frowning_face:

**Comment by raphaelmerx** [comment] 2017-02-25 03:03
I looked into https://github.com/mlavin/django-selectable/issues/179 and couldn't reproduce. Concerning the other issues you're linking to, they don't seem related to the master branch. Why would issuing a new minor version impact these issues?

**Comment by raphaelmerx** [comment] 2017-04-06 01:45
https://github.com/mlavin/django-selectable/issues/179 is fixed now. That was the only issue specific to Django 1.10. Would you consider issuing a new release?

**Comment by mlavin** [comment] 2017-04-09 14:30
Thank you for your effort to track down and resolve these issues. I've opened #186 to track the failures/remaining issues for 1.10/1.11 and I'm going to be resolving them in the next week or so.

**Comment by mlavin** [comment] 2017-04-14 13:22
v1.0.0 compatible with 1.10 is up on PyPi: https://pypi.python.org/pypi/django-selectable/1.0.0

**Closed by mlavin** 2017-04-14 13:22 UTC

**Comment by raphaelmerx** [comment] 2017-04-17 00:29
Thank you @mlavin for the new release, really appreciate it!

**Comment by mlavin** [comment] 2017-04-17 23:18
This release wouldn't have happened without your effort so thank you @raphaelmerx
