### ISSUE TITLE
Restrict multiple select items

### ISSUE THREAD

**Issue by X17** [mlavin/django-selectable#151] opened 2015-07-14 18:21 UTC
Is there any option to restrict the count of the multiselect items number let's say not more than 3.
I check the document couldn't find it, i guess it needs to be worked in js rather than backend.

Kindly help me on this. Thanks in advance

**Comment by mlavin** [comment] 2015-07-14 18:30
See #96 for some info on how this could be implemented by listening for the select/change events.

**Comment by mlavin** [comment] 2015-11-04 00:49
Closing as a duplicate of #96.

**Closed by mlavin** 2015-11-04 00:49 UTC
